### ISSUE TITLE
Remove `image:` selection on XCache

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/slate-catalog-stable#108]
SLATE applications cannot be allowed to select arbitrary images, such as:
 https://github.com/slateci/slate-catalog-stable/blob/master/charts/xcache/templates/deployment.yaml#L143

e.g.:
```
        - name: reporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/usr/local/sbin/run_cache_reporter.sh"]
```

Please make the image repository static. The tag may stay.

**Comment by adamhgriffith-uofu** [comment]
This is being addressed in #135.
