### ISSUE TITLE
Don't use latest in image tag

### ISSUE THREAD

**Issue by sthapa** [slateci/slate-catalog-stable#113]
https://github.com/slateci/slate-catalog-stable/blob/b68e007bb8a4682aefe35110983789a380ee3bd2/charts/faucet/templates/deployment.yaml#L32

Using latest for the tag isn't a best practice since it's hard to predict which version will be installed.  Either use a fixed version e.g. faucet/faucet:1.0 or use a selectable tag like "faucet/faucet:{{ .Values.ContainerTags.faucetVersion }}"

**Comment by adamhgriffith-uofu** [comment]
@polinaLyubavina, the decision we arrived at is to pin the version in the template file and not to include the ability to override it in the `values.yml` file.

**Comment by adamhgriffith-uofu** [comment]
This is being addressed in #133.
