### ISSUE TITLE
Complete stable app migration: cms-xcache

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-catalog-stable#38]
### General

1. Under **Development** on the right side of this page click **Create a branch**.
2. Check out the branch locally using the commands presented by the dialog that appears.
3. View the current stable SLATE application content for [cms-xcache](https://github.com/slateci/slate-catalog/tree/master/stable/cms-xcache/cms-xcache).
4. Migrate the content. Then locally perform static linting, other desired chart-specific testing, and governance checks.
5. When ready, submit a pull request on [slateci/slate-catalog-stable](https://github.com/slateci/slate-catalog-stable) with:
   * **Title:** (GitHub will auto-populate)
   * **Description:**  See <your github pull request title prefix/issue id, e.g. `#123`> for more details.
6. Squash-merge the pull request and delete the feature branch.
7. At this point GitHub workflows will publish the new chart and refresh the `dev` and `staging` API servers.
8. Try out the new application version using the `slate` remote client or by logging in to https://portal.dev.slateci.io and/or https://portal.staging.slateci.io respectively.

## Additional Resources

* [SLATE Catalog instructions on GDrive](https://docs.google.com/document/d/1GsDdktDw9NikCMuJYInKVzhoKIxuAz_N9NUfMIALpj0/edit#heading=h.6y6nuqavrw0)

**Comment by ivukotic** [comment]
already migrated
